line_length: 
- 300 # warning
- 500 # error
disabled_rules:
- file_length
- redundant_objc_attribute
- redundant_optional_initialization
- void_return
- trailing_whitespace
- redundant_discardable_let
- for_where
- force_cast
- blanket_disable_command
- comment_spacing
- multiple_closures_with_trailing_closure
- identifier_name
- function_body_length
