line_length: 
- 300 # warning
- 500 # error
disabled_rules:
- trailing_whitespace
- redundant_discardable_let
- for_where
- blanket_disable_command
- comment_spacing
- multiple_closures_with_trailing_closure
