# Uncomment the next line to define a global platform for your project

platform :ios, '13.0'

target 'iOS_waiter_NeoCafe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_waiter_NeoCafe

pod 'SVPinView', '~> 1.0'

end
